version: '2'
services:
  ihiwmanagement-app:
    image: ihiwmanagement
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://ihiwmanagement-mysql:3306/ihiwmanagement?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  ihiwmanagement-mysql:
    extends:
      file: mysql.yml
      service: ihiwmanagement-mysql
